### ISSUE TITLE
US-3: As a player, I want to be able to save my current game so that I can continue at a later time

### ISSUE THREAD

**Issue by CaeNGnp** [kenwongz/SimpCity#2]

**Comment by CaeNGnp** [comment]
^ Bad on my part, have wrongly tagged the issue which was closed together with the pull request.

Please conduct a test on this and decide if it's good to close, thanks!

@JSQJ @kenwongz

**Comment by kenwongz** [comment]
@Harish110 the feature is not working, i will move it to sprint 3

**Comment by kenwongz** [comment]
@CaeNGnp will be helping out with this feature as the issue has been unresolved for too long. @Harish110 has requested help as he could not get it to work.

**Comment by CaeNGnp** [comment]
^ As mentioned 2 comments up
