### ISSUE TITLE
US-8: As a player, I want to be able to see my current score during the game

### ISSUE THREAD

**Issue by kenwongz** [kenwongz/SimpCity#25]
Develop score view

**Comment by CaeNGnp** [comment]
Minor change of plan from standup meeting discussion: ~~I @CaeNGnp will handle writing the score calculation for House while refactoring the code. After that, @Harish110 will take over for the rest of the buildings~~

Edit: After discussion with @kenwongz,
- #28 will be assigned to me
- #38 tracks the individual progress of the score calculation
- #25 is assigned to @jordie007

**Comment by kenwongz** [comment]
Pushing it up to sprint 3 due to lack of time
