### ISSUE TITLE
US-15: As a player, I want to choose the city size to play in so that I can challenge myself across different map sizes

### ISSUE THREAD

**Issue by CaeNGnp** [kenwongz/SimpCity#29]
> - Note that you will have to adjust the number of available buildings appropriately for all the different city sizes.
> - There will also be a limit to the size of the city in relation to the number of choices.

- Develop logic
- Develop view

To discuss:
- Calculate remaining buildings dynamically
- Max grid size

**Comment by kenwongz** [comment]
We have discussed and finalized the formula

**Comment by CaeNGnp** [comment]
The formula discussed for each building copies was `floor( (width*height)/2 )`, scaling linearly from the current "16 cells, 8 copies".

**Comment by CaeNGnp** [comment]
Hey Scrum Master & QA, we still need to come to a final decision on the maximum city size.  @kenwongz  @JSQJ 

Let's bring this discussion to our Sprint Retrospective meeting tomorrow.👍

**Comment by kenwongz** [comment]
Yup, will do!

**Comment by kenwongz** [comment]
As per discussed, we think that 10x10 should be the limit for the city size
