### ISSUE TITLE
DoD: Test/debug mode

### ISSUE THREAD

**Issue by CaeNGnp** [kenwongz/SimpCity#41]
To facilitate easier testing, I am suggesting a test/debug mode that would modify the following:
- Disable "building must be adjacent to another" rule
- Allow all building types to be placed rather than any random 2

This would help alleviate difficulty in reproducing manual test cases.

Tagging SM and QA for discussion/approval - @JSQJ @kenwongz

**Comment by kenwongz** [comment]
why do u need to disable the "building must be adjacent to another rule"? That is one of the requirement for the project.

**Comment by CaeNGnp** [comment]
Hi, as mentioned in the original post:
> This would help alleviate difficulty in reproducing manual test cases.

I foresee debugging to be very complicated with this rule around, and if QA can verify if this is something we need I would appreciate it @JSQJ 

Last clarification: this is an optional toggle-able mode, not a change of requirement

**Comment by kenwongz** [comment]
ok, got it. i think its fine. @JSQJ need ur opinion on this issue

**Comment by JSQJ** [comment]
I think its fine, you can go ahead with it

**Comment by CaeNGnp** [comment]
Preview of debug mode:

![image](https://user-images.githubusercontent.com/93184095/150352981-22324925-ca5c-41c1-9c22-9cb0125169a9.png)
