### ISSUE TITLE
US-6: As a player, I want to be able to build different building types

### ISSUE THREAD

**Issue by kenwongz** [kenwongz/SimpCity#5]
Develop building type logic
Develop building placement logic
Develop updated game board UI view

**Comment by CaeNGnp** [comment]
Note requirement:
> The player may build on any square on Turn 1. In subsequent turns, buildings must be built orthogonally adjacent to existing buildings (i.e. Illegal placement: not next to existing building)

**Comment by kenwongz** [comment]
Close by #36 and #40
