### ISSUE TITLE
House is not loaded from save file

### ISSUE THREAD

**Issue by JSQJ** [kenwongz/SimpCity#53]

**Comment by JSQJ** [comment]
@Harish110  after saving game with house built, it is unable to load house when loading saved game

**Comment by Harish110** [comment]
@JSQJ Can you check again. To test restoring, go to the csv file change the variable to HSE and test. Saving game feature does not work however restoring does.

**Comment by kenwongz** [comment]
@Harish110 i have tested it too and found bug in the code. Pls check properly

**Comment by CaeNGnp** [comment]
Can confirm the bug too as of current main branch @ 9444dea316e0de0bcf6d9041714cf82788a9020a

**Comment by Harish110** [comment]
@kenwongz @JSQJ @CaeNGnp I have fixed the restore function in savingfeature branch . Please check and update me.
