### ISSUE TITLE
Scoring bug for shop

### ISSUE THREAD

**Issue by JSQJ** [kenwongz/SimpCity#71]
buildings off the same type adjacent to shop are counted as one point each instead of only one point

**Comment by JSQJ** [comment]
![image](https://user-images.githubusercontent.com/78250532/152299114-d712895e-a8c2-4f55-8793-90384b81dd06.png)
![image](https://user-images.githubusercontent.com/78250532/152299134-5d8229f5-066a-48fc-9785-878ccb97a387.png)

**Comment by JSQJ** [comment]
shop alone should be one point

**Comment by Harish110** [comment]
https://github.com/kenwongz/SimpCity/pull/73#issue-1123085554 
check this pull request for the fix
