### ISSUE TITLE
US - 8a Scoring logic for Beach

### ISSUE THREAD

**Issue by Harish110** [kenwongz/SimpCity#76]
"Scores 3 points if it is built on the left or right side of the city, or 1 point otherwise." 
Now it is only working for column A or D however if the citygrid size increases scores calculation are wrong.

**Comment by CaeNGnp** [comment]
Related #38 

SM @kenwongz, this should be High priority given the low story point. Agreeable?

**Comment by kenwongz** [comment]
Yup, i agree on the high priority. I have also added it into the Sprint 4 milestone
